artifact_location: file:///c:/repos/openstef-workshop/workshop-advanced/mlflow_trained_models/0
creation_time: 1708329720169
experiment_id: '0'
last_update_time: 1708329720169
lifecycle_stage: active
name: Default
