artifact_location: file:///c:/repos/openstef-workshop/workshop-beginner/mlflow_trained_models/0
creation_time: 1708330443474
experiment_id: '0'
last_update_time: 1708330443474
lifecycle_stage: active
name: Default
